repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.11.4
    hooks:
      - id: golangci-lint
        args: ["--config=.golangci.yaml"]
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-vet
      - id: go-build
      - id: go-unit-tests
      - id: go-mod-tidy
      - id: no-go-testing
  - repo: local
    hooks:
      - id: eslint_d
        name: eslint_d
        entry: eslint_d
        language: system
        files: \.(js|mjs|cjs)$
        pass_filenames: true
      - id: stylelint
        name: stylelint
        entry: npx stylelint
        language: system
        files: \.(css|scss)$
        pass_filenames: true
      - id: djlint
        name: djlint
        entry: djlint
        language: system
        files: \.(gohtml)$
        args: ["--ignore=H006,H013,H020"]
        pass_filenames: true
