services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    volumes:
      - ./deploy/data:/root/.local/share/gomarks
      - ./deploy/cache:/root/.cache/gomarks
    restart: unless-stopped

volumes:
  data:
    driver: local
  cache:
    driver: local
