services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    volumes:
        - ./data:/root/.local/share/gomarks
        - ./cache:/root/.cache/gomarks
    restart: unless-stopped
